### ISSUE TITLE
build number 0 needs to be fixed.

### ISSUE THREAD

**Issue by 183amir** [conda-forge/bob.ip.base-feedstock#4]
@conda-forge/core build number `0` was not pinned on a boost version. I am trying to fix this build: https://github.com/conda-forge/staged-recipes/pull/751 by downgrading `conda-build` but that version of `conda-build` pulls the build number 0 of `bob.ip.base`. Could you please either delete `bob.ip.base-2.0.9-py*_0` from `conda-forge` channel or hotfix its dependency on `boost` -> `boost 1.60.*`?
I did write a hotfix script here: https://github.com/conda-forge/conda-forge.github.io/pull/170 a while ago but it is not complete.

**Comment by 183amir** [comment]
The same for `bob.io.base` build numbers `0`, `1`, and `2`.

**Comment by jakirkham** [comment]
I'm confused `bob.ip.base` build number `0` doesn't seem to be dependent on `boost` at all.

**Comment by 183amir** [comment]
Because it was not listed as dependency but was being pulled during build because of their dependencies.

**Comment by jakirkham** [comment]
I see. Thanks for the clarification. So, they are linking to `boost`, but they just didn't list it explicitly. Correct?

**Comment by 183amir** [comment]
I mean boost was a dependency but I did not know at that time.

**Comment by 183amir** [comment]
Correct

**Comment by jakirkham** [comment]
Ok, so those are now removed.

FYI there didn't seem to be a build for `bob.ip.base` version 2.0.9 build number 0 on Mac. I don't remember if this was intentional (e.g. BLAS related) or unintentional (e.g. failed build).

**Comment by 183amir** [comment]
It's because I introduced the mac builds later.

**Comment by jakirkham** [comment]
Ok, that's fine.

Do things seem to be working for you now? Should we close this?

**Comment by 183amir** [comment]
Thank you but not yet. I need to test this later.

**Comment by 183amir** [comment]
This is fixed. Thanks.
